# Generated by Django 5.0.1 on 2024-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言管理', 'verbose_name_plural': '留言管理'},
        ),
    ]
