# Generated by Django 5.0.1 on 2025-03-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_alter_message_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="name",
        ),
    ]
