# Generated by Django 5.0.1 on 2025-03-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_remove_message_email_remove_message_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="name",
        ),
    ]
