# Generated by Django 5.0.1 on 2024-12-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articletype_options_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default=11, max_length=300, verbose_name='摘要'),
            preserve_default=False,
        ),
    ]
