# Generated by Django 5.0.1 on 2024-12-13 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_likes_article_abstract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客帖子管理', 'verbose_name_plural': '博客帖子管理'},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': '博客类别管理', 'verbose_name_plural': '博客类别管理'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AddField(
            model_name='articletype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帖子作者'),
            preserve_default=False,
        ),
    ]
