# Generated by Django 5.0.1 on 2025-03-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_article_options_alter_articletype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articletype",
            name="user",
        ),
    ]
