# Generated by Django 5.0.1 on 2024-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuminfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='album/', verbose_name='图片'),
        ),
    ]
