# Generated by Django 5.0.1 on 2024-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='链接名称')),
                ('url', models.CharField(max_length=200, verbose_name='链接地址')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '友情链接管理',
                'verbose_name_plural': '友情链接管理',
            },
        ),
    ]
